# -----------------------------------------------------------------------------
# MantisBT Travis-CI build configuration file
# -----------------------------------------------------------------------------

language: php

# -----------------------------------------------------------------------------
# Environment setup and test scripts execution
#

before_script:
  - chmod +x ./scripts/travis_before_script.sh
  
  - ./scripts/travis_before_script.sh

script:
  - chmod +x ./scripts/travis_script.sh
  - ./scripts/travis_script.sh

# -----------------------------------------------------------------------------
# What to build, and on which platforms
#

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - DB=mysql
  - DB=pgsql

branches:
  except:
    - master-2.0.x

matrix:
  include:
    # Add a specific build for Documentation
    # Note: we don't really care about the PHP version here, but we need
    # one version to trigger the build
    - env: DOCBOOK=1
      php: "5.5"

  allow_failures:

# -----------------------------------------------------------------------------
# Notifications
#

notifications:
  email:
    on_success: change
    on_failure: always

  irc:
    on_success: change
    on_failure: always
    channels:
       - "http://webchat.freenode.net/?channels=%23inforequest&uio=OT10cnVlJjExPTIwNQa5"
    skip_join: true
    template:
      - "Build #%{build_number}: %{repository} %{branch} (%{commit}) %{author} - %{message}"
      - "Build details: %{build_url}"
      - "Code Changes: %{compare_url}"
